#!/bin/bash
### kubernetes version ###
CUBE_VERSION=1.21

### APISERVER Loadbalancer & haproxy & vrrp IP ###
CUBE_ENV_PROXY_IP=""

### APISERVER Domain ###
CUBE_ENV_EXTERNAL_DNS=""

### CLUSTER NAME ###
CLUSTER_NAME=""

################
### ETCD ENV ###
################
HOSTNAME=`hostname`
NODE_IP=`ip addr | grep global | grep -E -v "docker|br-|tun" | awk '{print $2}' | cut -d/ -f1`
OS_TYPE=`grep ^NAME /etc/os-release | grep -oP '"\K[^"]+' | awk '{print $1}' | tr '[:upper:]' '[:lower:]'`
MASTER_HOSTNAME=("master01" "master02" "master03")
MASTER_NODE_IP=("" "" "")

### CUBE System Variable
CURRENT_PATH=`pwd`

### OS Version Check ####
if [ "${OS_TYPE}" == "centos" ]; then
  OS_VERSION=`cat /etc/centos-release | awk {'print $4'} | awk -F "." {'print $1 "." $2'}`
elif [ "${OS_TYPE}" == "amazon" ]; then
  OS_TYPE=amazon
elif [ "${OS_TYPE}" == "red" ]; then
  OS_TYPE=centos
  OS_VERSION=`cat /etc/redhat-release | awk '{print $7}'`
elif [ "${OS_TYPE}" == "ubuntu" ]; then
  OS_VERSION=`lsb_release -r | cut -f2 | awk -F "." {'print $1 $2'}`
elif [ "${OS_TYPE}" == "rocky" ]; then
  OS_VERSION=`cat /etc/os-release  | grep "^VERSION_ID" | awk -F"\"" '{print $2}'`
else
  echo "Please, Check your OS"
  exit 0
fi

##########################
### kubeadm config var ###
##########################
SERVICE_SUBNET="10.187.0.0/16"
POD_SUBNET="10.177.0.0/16"
CLUSTER_DNS="10.187.0.10"

### kubernetes cluster_ip ###
CUBE_ENV_CLUSTER_IP="10.187.0.1"

###############
### Network ###
###############
# install network env check "public" or "private"
NETWORK_TYPE=private

################
### GPU_NODE ###
################
# gpu_node env check "enable" or "disable"
GPU_NODE=disable

##############################
### Private Container Repo ###
##############################

### Private Repo "enable" or "disable"
PRIVATE_REPO=enable

### Private Repo URL
# example: IP:PORT
REPO_URL=""

### Private Container Repo URL
### HARBOR URL
HARBOR_URL=""

### Harbor Version
CUBE_HARBOR_VERSION=1.10.6

### CUBE WORK Directory
CUBE_WORK="/acorn"

### CUBE WORK Directory
CUBE_DATA="/data"

### CUBE TEMP Directory
CUBE_TMP="${CUBE_WORK}/acornsoft"

### CUBE EXEC Directory
CUBE_EXEC="${CUBE_WORK}/cocktail"

### AWS Check "enable" or "disable"
AWS_SERVER=disable

