#!/usr/bin/env bash

# Author : redicarus-jeong
# Date : 2022-06-30
# Desciption : This file is OS Environment setup for cune-5.2.3 and cocktail-4.6.6 install

### [Important] All information of master and node must be defined in /etc/hosts.

CURRENT_PATH=$(pwd)
SCRIPT_HOMEDIR=${CURRENT_PATH}/script
HOSTNAME=$(hostname)

COCKTAIL_USER="cocktail"
COCKTAIL_PASS="acorn!7942"

# The name of the interface you want to link with Cluser
IF_NAME="enp0s3"
IF_IPADDRESS=$(ip addr show dev ${IF_NAME} scope global |grep inet|awk '{print $2}'|cut -d'/' -f1)

# Name is in /etc/hosts is set.
REPOSITORY_HOSTNAME="repo" 
HARBOR_HOSTNAME="repo"
REPO_PORT="3777"
CUBE_HARBOR_VERSION="1.10.6"

### Enter the Kubernetes version to be installed through CUBE. Supports 1.18 ~ 1.21, stabilized on Cocktail 4.6.6 and recommended version is 1.21 Version
CUBE_VERSION="1.21"

INSTALL_MAIN_DIR="/APP"
CUBE_WORK="${INSTALL_MAIN_DIR}/acorn"
CUBE_DIR="${CUBE_WORK}/cube"
CUBE_DATA="${CUBE_WORK}/data"
CUBE_TEMP="${INSTALL_MAIN_DIR}/acornsoft"
CUBE_EXEC="${INSTALL_MAIN_DIR}/cocktail"
AWS_SERVER="disable"

# IP of Loadbalancer to which Master APISERVER will be connected (representative IP)
CUBE_ENV_PROXY_IP="172.27.120.49"

# Domain information to be connected to Master APISERVER IP
CUBE_ENV_EXTERNAL_DNS="master01.redicarus.com"
CUBE_ENV_EXTERNAL_DNS_LENGTH=${#CUBE_ENV_EXTERNAL_DNS[@]}

# Applied to installed kubernetes name, kubeadm config yaml
CLUSTER_NAME="redicarus-cluster"

#NODE_IP=$(ip addr | grep global | grep ${IF_NAME} | grep -E -v "docker|br-|tun" | awk '{print $2}' | cut -d/ -f1)
MAIN_MASTER_IP=$(ip addr | grep global | grep ${IF_NAME} | grep -E -v "docker|br-|tun" | awk '{print $2}' | cut -d/ -f1)
OS_TYPE=$(grep ^NAME /etc/os-release | grep -oP '"\K[^"]+' | awk '{print $1}' | tr '[:upper:]' '[:lower:]')


### OS Version Check
if [ "${OS_TYPE}" = "centos" ]; then
  OS_VERSION=$(cat /etc/centos-release | awk {'print $4'} | awk -F "." {'print $1 "." $2'})
elif [ "${OS_TYPE}" = "amazon" ]; then
  OS_TYPE=amazon
elif [ "${OS_TYPE}" = "red" ]; then
  OS_TYPE=centos
  OS_VERSION=$(cat /etc/redhat-release | awk '{print $7}')
elif [ "${OS_TYPE}" = "ubuntu" ]; then
  OS_VERSION=$(lsb_release -r | cut -f2 | awk -F "." {'print $1 $2'})
elif [ "${OS_TYPE}" = "rocky" ]; then
  OS_VERSION=$(cat /etc/os-release  | grep "^VERSION_ID" | awk -F"\"" '{print $2}')
else
  echo "Please, Check your OS"
  exit 0
fi


# Value to be applied to "podSubnet" of kubeadm - Subnet value to be used in Pod's Network, also applied to "CALICO_IPV4POOL_CIDR" setting when Calico is installed.
POD_SUBNET="10.240.0.0/16"

# Value to be applied to "serverSubnet" in kubeadm - Used by Cluster Subnet in Kubernetes
SERVICE_SUBNET="10.100.0.0/16"

### Network environment definition. "public" or "private"
NETWORK_TYPE=private

### Defining whether or not to use GPU. "enable" or "disable"
GPU_NODE=disable

### Define whether or not to use Harbor in a private environment (to be removed). "enable" or "disable"
PRIVATE_REPO=enable

# The names of master in /etc/hosts. name is lowcase ( format = array )
MASTER_HOSTNAME=("master01")         # ex) MASTER_HOSTNAME=("master01" "master02" "master03")
# The names of node in /etc/hosts.   ( format = array )
NODE_HOSTNAME=("noe01")             # ex) NODE_HOSTNAME=("node01" "node02" "node03")
NODE_NAME_PREFIX="node"


#########################################################################################################
######### NOTICE : The environment variables below are automatically defined. do not touch..!! ##########
#########################################################################################################

# IP addresses of all masters in /etc/hosts. ( format = array )
#MASTER_NODE_IP=("10.10.10.111")      # ex) MASTER_NODE_IP=("10.10.10.111" "10.10.10.112" "10.10.10.113")
MASTER_NODE_IP=()
for MASER_NAME in ${MASTER_HOSTNAME[@]}
  do
      MASTER_IP="$(grep ${MASER_NAME} /etc/hosts |sort -u|head -1|awk 'NR==1 {print $1}')"
      MASTER_NODE_IP+=("${MASTER_IP}")
done

NODE_NODE_IP=()
for NODE_NAME in ${NODE_HOSTNAME[@]}
  do
      NODE_IF_IP="$(grep ${NODE_NAME} /etc/hosts |sort -u|head -1|awk 'NR==1 {print $1}')"
      NODE_NODE_IP+=("${NODE_IF_IP}")
done
# Value to be applied to "clusterDns" of kubeadm - Configured by referring to the CIDR value of serverSernet
# EX) If SERVICE_SUBNET is 172.0.0.0/16, CLUSTER_DNS is 172.0.0.10 and CUBE_ENV_CLUSTER_IP is 172.0.0.1
#CLUSTER_DNS="10.100.0.10"
CLUSTER_DNS="$(echo ${SERVICE_SUBNET} | awk -F'.' '{print $1"."$2"."$3".10"}')"

# CLUSTER_IP value used for certificate
#CUBE_ENV_CLUSTER_IP="10.100.0.1"
CUBE_ENV_CLUSTER_IP="$(echo ${SERVICE_SUBNET} | awk -F'.' '{print $1"."$2"."$3".1"}')"

### About Yum or APT Private REPO in Private Environment.  example: IP:PORT
REPO_URL="$(grep ${REPOSITORY_HOSTNAME} /etc/hosts |sort -u|head -1|awk 'NR==1 {print $1}'):${REPO_PORT}"

### Private Container Repo URL. [ HARBOR URL ]
HARBOR_URL="$(grep ${HARBOR_HOSTNAME} /etc/hosts |sort -u|head -1|awk 'NR==1 {print $1}')"

ETCD_MEMBER_COUNT=$(sudo ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379  \
                                                      --cacert=/etc/kubernetes/pki/etcd/ca.crt  \
                                                      --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt  \
                                                      --key=/etc/kubernetes/pki/etcd/healthcheck-client.key  \
                                                      member list 2>/dev/null | wc -l)

### Global Variable alias
CUBE_TMP=${CUBE_TEMP}
NODE_IP=${IF_IPADDRESS}